# -*- coding: utf-8 -*-
"""PDF_Reader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11epcs0MNAQWsqQVBGHUxxqjj-Wz6J5BT
"""

def pdfreader(Number_Train_files,file_list,PyPDF2):

  pages=[]

  for i in range(Number_Train_files):
    pdfReader = PyPDF2.PdfFileReader(open(file_list[i],'rb'))
    n1=pdfReader.numPages
    pages.append(n1)
  
  All_Docs=[] 

  for j in range(len(file_list)):
    pdfReader = PyPDF2.PdfFileReader(open(file_list[j],'rb'))
    file_text=[] #takes string of page text
    for i in range(pages[j]):
      pageObj = pdfReader.getPage(i)
      a=pageObj.extractText()
      file_text.append(a)
    
    All_Docs.append(file_text)

  return pages,All_Docs
  ## All_Docs[i][j] is j-th page of i-th file